import streamlit as st
from nba_api.stats.static import players
from nba_api.stats.endpoints import playergamelog
import pandas as pd
import numpy as np
from scipy.stats import norm

# --- Configuração da Página (Visual Clean e Focado) ---
st.set_page_config(page_title="Sniper NBA Mobile", layout="centered")

st.markdown("""
    <style>
        .big-font { font-size:30px !important; font-weight: bold; color: #4CAF50; }
            .risk-alert { color: #FF5252; font-weight: bold; }
                </style>
                    """, unsafe_allow_html=True)

                    st.title("🏀 Sniper NBA Mobile")
                    st.caption("Foco. Disciplina. Probabilidade.")

                    # --- Inputs do Usuário (A entrada de dados) ---
                    player_name_input = st.text_input("Nome do Jogador (Ex: LeBron James)", "")
                    line_bet = st.number_input("Linha da Casa de Aposta (Pontos)", min_value=0.5, step=0.5)
                    opponent = st.text_input("Contra qual time? (Apenas para registro)", "")
                    local_game = st.selectbox("Onde é o jogo?", ["Casa", "Fora"])

                    # --- Botão de Ação ---
                    if st.button("RODAR ALGORITMO PREDITIVO"):
                        if player_name_input:
                                try:
                                            with st.spinner('Buscando dados na API da NBA...'):
                                                            # 1. Buscar ID do Jogador
                                                                            nba_players = players.get_players()
                                                                                            player_dict = [p for p in nba_players if p['full_name'].lower() == player_name_input.lower()]
                                                                                                            
                                                                                                                            if not player_dict:
                                                                                                                                                st.error("Jogador não encontrado. Verifique a grafia (Ex: 'Jayson Tatum').")
                                                                                                                                                                else:
                                                                                                                                                                                    player_id = player_dict[0]['id']
                                                                                                                                                                                                        
                                                                                                                                                                                                                            # 2. Buscar últimos jogos (Game Log)
                                                                                                                                                                                                                                                gamelog = playergamelog.PlayerGameLog(player_id=player_id, season='2024-25')
                                                                                                                                                                                                                                                                    df = gamelog.get_data_frames()[0]
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                            # Pegar apenas os últimos 20 jogos para análise de momento
                                                                                                                                                                                                                                                                                                                                last_20 = df.head(20).copy()
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        # 3. Cálculos Estatísticos (A Matemática do Trader)
                                                                                                                                                                                                                                                                                                                                                                                            media_pts = last_20['PTS'].mean()
                                                                                                                                                                                                                                                                                                                                                                                                                desvio_padrao = last_20['PTS'].std()
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Cálculo Z-Score (Probabilidade Normal)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Qual a chance de fazer MAIS que a linha?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                z_score = (line_bet - media_pts) / desvio_padrao
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    probabilidade_over = (1 - norm.cdf(z_score)) * 100
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # --- Exibição dos Resultados ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.markdown("---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.subheader(f"Análise: {player_dict[0]['full_name']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            col1, col2 = st.columns(2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                col1.metric("Média (20J)", f"{media_pts:.1f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    col2.metric("Volatilidade", f"{desvio_padrao:.1f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.markdown("### Probabilidade Estatística")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Lógica de Cores tipo "Farol"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color = "red"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            recommendation = "NÃO ENTRAR (EV Negativo)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if probabilidade_over > 65:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color = "#4CAF50" # Verde
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    recommendation = "ALTA PROBABILIDADE (Sniper)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif probabilidade_over > 50:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color = "orange"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        recommendation = "NEUTRO / RISCO MÉDIO"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.markdown(f'<p class="big-font" style="color:{color}">{probabilidade_over:.2f}% de bater o Over {line_bet}</p>', unsafe_allow_html=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.info(f"Veredito Matemático: **{recommendation}**")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Gestão de Risco (Mentalidade Estoica)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if probabilidade_over < 55:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.warning("⚠️ Alerta: A probabilidade está baixa. Lembre-se da gestão de banca. Não force a entrada.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Mostrar últimos 5 jogos para conferência
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.write("Últimos 5 Jogos:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.dataframe(last_20[['GAME_DATE', 'MATCHUP', 'PTS']].head(5))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.error(f"Erro ao processar: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.warning("Digite o nome do jogador para começar.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        